# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ef7da353d1a76cd123807a7d61c363b26e3f288397f4c9494d423d23861b32abc2507c1afaa47e51b8d0d9f6c54ac822bf5810ba6943ab7b2a4c0cf513ba37

test:
  secret_key_base: ba9a7efdfe2062d318ca04177a2d1aee618f52309e2da6bed0a9f8d236ca91d823e3eb4eefea1553d7c180029f11655c9245bea6093ba4f95c6f63fae1d2c2bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
